language: python
python:
- 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
install:
- pip install .
script: python -m unittest discover
after_success:
  - coverage run -m unittest discover
  - bash <(curl -s https://codecov.io/bash)
